# netlify.toml

[build]
  base = "path/to/your/project"  # Change to the path of your project
  command = "cd client && npm run dev && python app.py" # Adjust the build command based on your project setup
  publish = "path/to/your/project/dist" # Adjust the publish directory based on your project setup

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
